require at least PHPUnit 5.7
Fatal error: A void function must not return a value in …/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(305) : eval()'d code on line 30