require Mockery at least 0.9.9
Fatal error: A void function must not return a value in …/mockery/mockery/library/Mockery/Loader/EvalLoader.php(16) : eval()'d code on line 762